<?php
/**
 * @file
 * Allow Backdrop messages to be manually, or automatically, dismissed.
 */

/**
 * Implements hook_config_info().
 */
function dismiss_config_info() {
  return array(
    'dismiss.settings' => array(
      'label' => t('Dismiss settings'),
      'group' => t('Configuration'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function dismiss_menu() {
  return array(
    'admin/config/user-interface/dismiss' => array(
      'title' => 'Dismiss',
      'description' => 'Configure Dismiss settings.',
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('dismiss_admin_form'),
      'access arguments' => array('administer site configuration'),
    ),
  );
}

/**
 * Implements hook_preprocess_page().
 */
function dismiss_preprocess_page(&$variables) {
  // Pass fadeout value to JS.
  backdrop_add_js(array(
    'dismiss' => array(
      'fadeout' => config_get('dismiss.settings', 'fadeout'),
    ),
  ), 'setting');
}

/**
 * Form constructor for Dismiss administrative settings.
 */
function dismiss_admin_form($form, &$form_state) {
  $config = config('dismiss.settings');
  $form['#config'] = 'dismiss.settings';

  $form['fadeout'] = array(
    '#type' => 'number',
    '#title' => t('Display time'),
    '#description' => t("The length of time (in milliseconds) messages are displayed before being automatically dismissed. Enter '0' to disable this behavior."),
    '#default_value' => $config->get('fadeout'),
    '#min' => 0,
    '#max' => 999999,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}
