<?php
/**
 * @file
 * Allow Backdrop messages to be manually, or automatically, dismissed.
 */

/**
 * Implements hook_config_info().
 */
function dismiss_config_info() {
  return array(
    'dismiss.settings' => array(
      'label' => t('Dismiss settings'),
      'group' => t('Configuration'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function dismiss_menu() {
  return array(
    'admin/config/user-interface/dismiss' => array(
      'title' => 'Dismiss',
      'description' => 'Configure Dismiss settings.',
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('dismiss_admin_form'),
      'access arguments' => array('administer site configuration'),
    ),
  );
}

/**
 * Implements hook_preprocess_page().
 */
function dismiss_preprocess_page(&$variables) {
  $config = config('dismiss.settings');
  $module_path = backdrop_get_path('module', 'dismiss');
  $scope = $config->get('scope');
  $type = $config->get('inline');

  // Add CSS.
  backdrop_add_css($module_path . '/css/dismiss.base.css');

  // Add JS.
  $code = $module_path . '/js/dismiss.js';
  if ($type == 'inline') {
    $code = file_get_contents($code);
  }
  backdrop_add_js($code, array(
    'type' => $type,
    'scope' => $scope,
    'every_page' => TRUE,
  ));

  // Pass fadeout value to JS.
  backdrop_add_js(array(
    'dismiss' => array(
      'fadeout' => $config->get('fadeout'),
    ),
  ), 'setting');
}

/**
 * Form constructor for Dismiss administrative settings.
 */
function dismiss_admin_form($form, &$form_state) {
  $config = config('dismiss.settings');
  $form['#config'] = 'dismiss.settings';

  $form['scope'] = array(
    '#type' => 'select',
    '#title' => t('Script location'),
    '#description' => t("Where to place the script on the page. 'Footer' is generally recommended."),
    '#options' => array(
      'header' => t('Header'),
      'footer' => t('Footer'),
    ),
    '#default_value' => $config->get('scope'),
  );
  $form['inline'] = array(
    '#type' => 'select',
    '#title' => t('Script type'),
    '#description' => t("The type of javascript to be added to the page. 'Inline' is generally recommended for performance."),
    '#options' => array(
      'inline' => t('Inline'),
      'file' => t('File'),
    ),
    '#default_value' => $config->get('inline'),
  );
  $form['fadeout'] = array(
    '#type' => 'number',
    '#title' => t('Display time'),
    '#description' => t("The length of time (in milliseconds) messages are displayed before being automatically dismissed. Enter '0' to disable this behavior."),
    '#default_value' => $config->get('fadeout'),
    '#min' => 0,
    '#max' => 999999,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}
